# .goreleaser.yml
# Build customization
builds:
  - binary: squadron
    main: ./cmd/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    goarm:
      - 7
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/foomo/squadron/cmd/actions.version={{.Version}}
archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
changelog:
  sort: asc
  filters:
    exclude:
      - "^chore:"
      - "^docs:"
      - "^test:"
      - "^wip:"
brews:
  # Repository to push the tap to.
  - tap:
      owner: foomo
      name: homebrew-squadron
    caveats: "squadron -h"
    homepage: "https://github.com/foomo/squadron"
    description: "CLI utility manage infrastructure as code with helm"
