# .goreleaser.yml
# Build customization
builds:
  - binary: squadron
    main: ./cmd/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    goarm:
      - 7
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/foomo/squadron/cmd/actions.version={{.Version}}

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

changelog:
  filters:
    exclude:
      - "^wip"
      - "^test"
      - "^docs"
      - "^chore"
      - "^style"
      - "go mod tidy"
      - "merge conflict"
      - "Merge pull request"
      - "Merge remote-tracking branch"
      - "Merge branch"
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Dependency updates
      regexp: '^.*?(feat|fix)\(deps\)!?:.+$'
      order: 100
    - title: "Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 150
    - title: "Security"
      regexp: '^.*?sec(\([[:word:]]+\))??!?:.+$'
      order: 200
    - title: "Performace"
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 250
    - title: Other
      order: 999

brews:
  # Repository to push the tap to.
  - tap:
      owner: foomo
      name: homebrew-squadron
    caveats: "squadron -h"
    homepage: "https://github.com/foomo/squadron"
    description: "CLI utility manage infrastructure as code with helm"
