project_name: squadron

release:
  github:
    owner: foomo
    name: squadron
  prerelease: auto

builds:
  - binary: squadron
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    goarm:
      - '7'
    env:
      - CGO_ENABLED=0
    main: ./cmd/main.go
    flags:
      - -trimpath
    ldflags: -s -w -X github.com/foomo/squadron/cmd/actions.version={{.Version}}

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

changelog:
  use: github-native

brews:
  # Repository to push the tap to.
  - repository:
      owner: foomo
      name: homebrew-tap
    caveats: "squadron -h"
    homepage: "https://github.com/foomo/squadron"
    description: "CLI utility manage infrastructure as code with helm"
    test: |
      system "#{bin}/squadron --version"
