apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  namespace: {{ .Release.Namespace }}
spec:
  tls:
    - hosts: [ "foo.com" ]
      secretName: foo-com-cert
  rules:
    - host:  foo.com
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: {{ $.Release.Name }}
                port:
                  name: http
                  number: 80
