name: goreleaser

on:
  push:
    tags:
      - v*.*.*

env:
  GO_VERSION: 1.18
  GOLANGCI_LINT_VERSION: v1.45.2

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    env:
      GOFLAGS: -mod=readonly
      GOPROXY: https://proxy.golang.org
    steps:
      - uses: actions/checkout@v3
      - run: git fetch --prune --unshallow
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: golangci/golangci-lint-action@v3.1.0
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
      - uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
