name: Release Tag

on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:

env:
  GOFLAGS: -mod=readonly
  GOPROXY: https://proxy.golang.org

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: git fetch --force --tags

      - uses: actions/setup-go@v5
        with:
          check-latest: true
          go-version-file: 'go.mod'

      - uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
