name: checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  merge_group:
    branches: [ master ]
  workflow_dispatch:

env:
  GOFLAGS: -mod=readonly
  GOPROXY: https://proxy.golang.org

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          check-latest: true
          go-version-file: 'go.mod'

      - uses: golangci/golangci-lint-action@v3

      - name: Run tests
        run: go test -v ./...
        env:
          SHELL: "/bin/zsh"
